export const CDN_URL_FOOD =  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320/" 
export const LOGO_CDN = "https://image.similarpng.com/very-thumbnail/2020/06/Restaurant-logo-with-chef-drawing-template-on-transparent-background-PNG.png"
export const swiggy_menu_api_URL ="https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=8.5270567&lng=76.9419295&restaurantId="
export const restaurant_data_api_URL = "https://www.swiggy.com/dapi/restaurants/list/v5?lat=8.5270567&lng=76.9419295&collection=80386&tags=layout_BAU_Contextual%2Cputtu&sortBy=&filters=&type=rcv2&offset=0&page_type=null"
export const BANNER_FOOD_URL = "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/"
export const BANNER_FOOD_MENU = "https://www.swiggy.com/dapi/restaurants/list/v5?lat=8.5270567&lng=76.9419295&collection=" 